adafruit/ci-arduino

- install.sh
Verifies all examples, and outputs results in a easier to read format. Also adds JSON output so the example & platform build status can be accessed programmatically.
> Build All Examples

- install.sh
Would be nice for the hackster.io challange.
> Add SAMD / Zero (MKR1000) support

- install.sh
> DM: adding cplay platforms

- doxy_gen_and_deploy.sh
fix travis for existing doxyfile
> DM: fix doxygen for existing doxyfile

- install.sh
> add SAMD M0 only build platform

- install.sh
Simple change to add the mega2560 platform to the list of main platforms.
> Add mega2560 to main platforms

- .travis.yml
- README.md
- example_travis.yml
- install.sh
> Travis cache

- .travis.yml
- README.md
- example_travis.yml
- install.sh
I would like to know your opinion, in certain cases this does speed up significantly (after 2nd pass).
[Travis of my repo](https://travis-ci.org/CornyjK/travis-ci-arduino)
This PR:
- Adds support for caching.
- Makes X and their opposites colored.
- Cleans-up some stuff.
> Add caching support

- README.md
- install.sh
Bump version in ´install.sh´ and add a note about version variable.
@ladyada
> Version bump + note

- doxy_gen_and_deploy.sh
> ftp.stack.nl is gone; change download location

- install.sh
Forgot to remove debugging flag.
> oops, remove --verbose

- install.sh
Adding Metro M4 AirLift Lite to IO Platforms.
> Add Metro M4 AirLift to IO_Platforms

- install.sh
> Add nrf5x to build platform

- .travis.yml
> add nrf52840 self-test, use addon pip3 to install adafruit-nrfutil

- README.md
Hey, I've added the note about installing multiple libraries again without deleting the surrounding content ;)
And as a seperate commit, as you wshed the chapter about installing external libraries.
> Note about installing multiple libraries

- README.md
see the description of the commit
> Talking about ARDUINO_IDE_VERSION

- install.sh
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:
the code.
- **Please run any tests or examples that can exercise your modified code.**  We
strive to not break users of the code and running tests/examples helps with this
process.
Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be …
> Added HalloWing M4 to Arcade Platforms

- install.sh
I'm hoping this might be what's missing.
> Adding some options to CPB like the nRF52840 has

- README.md
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:
the code.
Only documentation change for better syntax highlighting.
None known.
- **Please run any tests or examples that can exercise your modified code.**  We
strive to not break users of the code and running tests/examples helps with this
process.
No testing, but did manually view …
> Added markdown code language specifications for syntax highlighting.

- .github/workflows/githubci.yml
- .travis.yml
- install.sh
Reverts adafruit/travis-ci-arduino#58
Reverting due to #59
> Revert "Make it work with Github CI"

- build_platform.py
There is a few commits in between for testing, please do "squash and merge"
> add metro_m0/m4_tinyusb platform

- install.sh
As of today, the latest Arduino IDE version is **1.8.11** which includes
several bug-fixes and enhancements.
> Use the latest Arduino IDE version

- doxy_gen_and_deploy.sh
This will let libraries that have the code in src to work with the current doxygen setup.
> Added option to set input for doxygen

- build_platform.py
- install.sh
Please review the changes carefully, I edited this by rote, adding Grand Central M4 based on other boards' config.
> Add Grand Central M4

- README.md
Updates Readme with proper file path
> Fix typo, add note about Github actions

- actions_install.sh
dont remember why we pinned it :shrug:
> try changing to unpinned

- .github/workflows/githubci.yml
- build_platform.py
Pi Pico and Adafruit Feather, standard speed & flash size for each
> Add RP2040 (Philhower core)

- build_platform.py
Reverts #155. The issue with the BSP seems resolved:
https://github.com/SpenceKonde/megaTinyCore/issues/968
> Revert megatinycore BSP URL

- build_platform.py
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:
the code.
- **Please run any tests or examples that can exercise your modified code.**  We
strive to not break users of the code and running tests/examples helps with this
process.
Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be …
> Add MatrixPortal S3 to Build Platforms

- build_platform.py
remove drazzy so we don't fail on installing the BSP json file
> until BSP link is fixed

- all_platforms.py
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:
the code.
- **Please run any tests or examples that can exercise your modified code.**  We
strive to not break users of the code and running tests/examples helps with this
process.
Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be …
> Add Qualia S3 RGB666

- all_platforms.py
> add metro esp32s3

- build_platform.py
This stops the arduino library dependencies being installed if an existing match is found, which allows us to override the dependencies from latest version to a manually installed version (during a precursor build step)
Needed to allow specifying version 6.x of ArduinoJson rather than latest 7 (breaking changes)
We do this by cloning the 6.x branch into the arduino libraries folder (with correct library name),
and the Install Arduino Dependencies step then skips any existing libraries:
1. https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/actions/runs/7462582364/job/20305404144#step:7:9
2. https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/actions/runs/7462582364/job/20305404144#step:11:25
Tagging @ladyada for review
> Update build_platform.py - Don't install installed arduino libs

- all_platforms.py
@brentru this one should be okay :)
> Add ItsyBitsy ESP32

- build_platform.py
add support for .skip.txt which list each platform per line, this help to make excluding multiple platform easier/cleaner
> support .skip.txt each platform per line

- all_platforms.py
This might fix problems seen in adafruit_learning_system_guides for the memento board...
> use standard esp32 bsp3 for pycamera

- all_platforms.py
This helps with https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/2837 (see #188)
> Add some trinkeys

- all_platforms.py
curious if TRRStrinkey vs trrstrinkey is what is causing the variant file to not be found on learn
> edit trrs trinkey

- all_platforms.py
adding Feather RP2040 Adalogger to `all_platforms.py`
> add feather rp2040 adalogger

- all_platforms.py
Adds https://www.adafruit.com/product/5933
> Add C6 definitions

- all_platforms.py
This will let us start building useful firmware images during CI in Adafruit_Floppy
ping @ladyada
> add floppsy to platforms

- all_platforms.py
> Delete unused boards

- all_platforms.py
This adds the two build targets for the Mini Sparkle Motion and full-sized edition
> Add Sparkle Motion boards
