install.sh
Currently the build output looses the newlines. This is due to the two missing double quotes.
=> Chg: Add double quotes to output the newlines

install.sh
A (new) board can be included with its full qualifier (e.g.: arduino:avr:uno).
`script:`
`  - build_platform arduino:avr:uno`
`  - build_platform leonardo`
`  - build_platform esp8266:esp8266:nodemcu`
The build will fail, if the identifier is invalid, because the board will not loaded and exits with an error.
=> Chg: Allow use of any board-id

README.md, example_travis.yml
Updated the Arduino IDE versions in the example Travis configurations.
More specifically, the exmple configurations found in README.md and example_travis.yml
=> Bump Arduino IDE version to 1.8.7

.travis.yml, install.sh
Fixes part of #34. esp8266-2.5.0-beta1 changed the menu option names.
=> update esp8266 option names

install.sh
This was supposedly fixed upstream after 2.5.0-beta1. They're on beta3 anyway now.
https://github.com/esp8266/Arduino/issues/5483.
I _think_ this will be OK, since the issue about `signing.py` not having execute permission was some kind of side effect of another bug.
=> stop trying to fix esp8266 2.5.0-beta1 permission problem

README.md, install.sh
Some projects may only need to be built on certain platforms, so it's a waste to install _all_ platforms when only one or two will be used. This change cut down our build time from ~7 minutes to ~2 minutes.
This change is non-breaking. If the `INSTALL_PLATFORMS` environment variable is unset, all platforms will be installed.
Here is an example build configuration:
```
language: python
python:
- "3.7"
cache:
directories:
- ~/.arduino15/packages/
before_install:
- export INSTALL_PLATFORMS="esp32"
- source <(curl -SLs https://raw.githubusercontent.com/andrewda/travis-ci-arduino/custom-install/install.sh)
install:
- arduino --install-library "PID"
script:
- build_platform esp32
```
And an example of it passing CI [here](https://travis-ci.com/SouthEugeneRoboticsTeam/ursa/builds/117387932#L197-L …
=> Allow custom installation

README.md
A simple README change to fix a ` [!: command not found` error when using the external library download script.
=> Add space in external libraries bash script

README.md, install.sh
Preserve the temporary files (e.g. '.hex') so they can be found
at a deterministic location and be deployed if there's a need to.
This can be particularly useful in cases where the user needs
to release the compiled binaries or push them to a deployment
pipeline.
The patch introduces a new variable, i.e. `$ARDUINO_HEX_DIR`,
that exposes in a deterministic manner the directory in which
the temporary files are located. Further details on how to use
this variable can be found in the updated `README.md`.
=> Preserve temporary files after compilation

install.sh
Added the Circuit Playground BlueFruit and Adafruit version of CircuitPlayground Express to the CPlay_Platforms group. Also added a missing comma. This is needed for adding the gizmo tests to the ST7735/ST7789 driver.
=> Added Adafruit CircuitPlayground Express and Bluefruit

README.md, example_travis.yml, install.sh
Updated the Arduino IDE version to 1.8.10.
This also aligns the Arduino IDE version used in the README, example Travis configuration and install script. Previously they were either referring to version 1.8.7 or 1.8.9.
Full release notes for the Arduino IDE 1.8.10 are found [here](https://www.arduino.cc/en/Main/ReleaseNotes).
=> Bump Arduino IDE version to 1.8.10

README.md, example_travis.yml
As the travis example tests on ```build_main_platforms``` which includes nrf52840,  ```pip3``` should be installed in travis example as installation of ```adafruit-nrfutil``` requires ```pip3```.
This PR also updates the travis example in README, which should be same as https://github.com/adafruit/ci-arduino/blob/master/example_travis.yml.
=> Install required pip3 in travis example and update the example in README

build_platform.py
Previously, Arduino SAMD Boards was installed whenever the script was run for one of the Adafruit SAMD Boards.
Adafruit SAMD Boards doesn't have a dependency on Arduino SAMD Boards, so this only slows down the CI run.
the code.
I removed the code that installs Arduino SAMD Boards whenever the code is being compiled for one of the Adafruit SAMD Boards.
This change would only cause a problem if Adafruit SAMD Boards changed to having a dependency on Arduino SAMD Boards at some …
=> Remove code for unnecessary Adafruit SAMD Boards platform dependency

actions_install.sh
I've tested this on a fork of this library and locally. Arduino changed the install script, so now it won't work unless you specify the version.
=> Fix actions install script

build_platform.py
I noticed this message during an otherwise successful build of our arduino-CAN fork:
```
/home/runner/work/arduino-CAN/arduino-CAN/ci/build_platform.py:183: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```
This should resolve the problem.
=> Resolve warning that will affect Python 3.10 compatibility

build_platform.py
Adding patch for allowing the MetroX arduino example repo to use `.deps` to handle dependencies and search for examples within all directory paths, similar to Learning System Guide repository.
Verified working with an active MetroX pull request running against a staged version of the ci script on `brentru/ci-arduino` https://github.com/brentru/METROX-Examples-and-Project-Sketches-1/actions/runs/416213086
=> Patch for MetroX Arduino Repo

doxy_gen_and_deploy.sh
This pull request addresses issue #74 (doxy\_gen\_and\_deploy.sh assumes it run on Travis). The commit message created by the script now has relevant information both when running on Travis and when running on GitHub actions.
I tested the change on a fork of RTClib. The [commit generated by Travis][travis] looks like this:
```text
Author: Doxygen CI <ci-arduino@invalid>
Date:   Tue Dec 29 22:24:39 2020 +0000
Deploy docs to GitHub Pages from commit 6b806f2db3
Commit: 6b806f2db31aa01813a9194e8dcd33bb03e63a1a
Travis build: 4
```
The [commit generated by GitHub actions][actions]:
```text
Author: Doxygen CI <ci-arduino@invalid>
Date:   Tue Dec 29 22:14:38 2020 +0000
Deploy docs to GitHub Pages from commit 6b806f2db3
Commit: 6b806f2db31aa01813a9194e8dcd33bb03e63a1a
GitHub Actions run: 451559241 …
```
=> Format documentation commit in GitHub actions

build_platform.py
add feather m4 can to platform list for ci on library check such as tinyusb arduino
=> add feather m4 can to platform list

build_platform.py
- update BUILD_DIR to be able to run it locally
- add `pico_rp2040_tinyusb` and `feather_rp2040_tinyusb`
- add optional `--wall` option for build ci
- The ci now always build with all warnings, in case of `--wall` option is present. warning is counted as error. 
- Otherwise the build will pass but the warning message is printed so that we could fix it gradually.
=> add optional --wall option for ci

build_platform.py
Adding Metro M4 AirLift Lite w/tinyusb stack to platform list.
=> Add Platform - Metro M4 AirLift w/TinyUSB stack

build_platform.py
This PR use the same library name when making an symlink to `Arduino/libraries` location. The reason is some libraries is included by core BSP e.g `Adafruit_TinyUSB_Arduino`. Make a symlink with generic name ` Adafruit_Test_Library` will cause arduino-cli pick the one included in BSP due to better name win criteria (Folder Name Priority) when running ci.
CI log 
```
Multiple libraries were found for "Adafruit_TinyUSB.h"
Used: /home/runner/.arduino15/packages/adafruit/hardware/nrf52/0.24.0/libraries/Adafruit_TinyUSB_Arduino
Not used: /home/runner/Arduino/libraries/Adafruit_Test_Library
```
Arduino Dependency Resolution
```
If multiple libraries contain a file that matches the #include directive, the priority is determined by applying the following rules, one by one in this order, until a …
```
=> make symlink with library name rather than 'Adafruit_Test_Library'

actions_install.sh, build_platform.py
This pull request adds support for exporting compiled examples from CI-Arduino.
Compilation:
- If a `.platform.generate` file is included in the `libraryName/examples` folder, Arduino-CLI will export the compiled example as a `.hex` file. 
- Platforms that support the UF2 file format will additionally pack the .hex into a .uf2 file.
- The arduino-cli version has been updated to v18.3
----
Distribution:
- Repositories that include an upload-artifact step (see below) will attach the `.hex` and `.uf2` files to the build in a .zip file (Example, under "Artifacts": https://github.com/brentru/Adafruit_SI1145_Library/actions/runs/1222715452)
For example, the repository above contains two generation files: `.uno.generate` and `.metro_m4.generate`. The AVR (uno) only produces a .hex file:
And the …
=> Add support for exporting compiled examples 

build_platform.py
This started failing in the Learning System Guides when I added `.generate` files:
```
Traceback (most recent call last):
build dir: /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides
File "/home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/ci/build_platform.py", line 44, in <module>
os.rmdir(BUILD_DIR + "/ci/examples/Blink")
OSError: [Errno 39] Directory not empty: '/home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/ci/examples/Blink'
Found learning system repo
```
=> Remove the whole blink example folder

build_platform.py
Should fix
```
File "/home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/ci/build_platform.py", line 219, in install_platform
install_platform("arduino:avr")
TypeError: install_platform() missing 1 required positional argument: 'platform_name'
```
by making `platform_name` key optional instead of required
=> Fix positional argument issue with AVR installation call

build_platform.py
Fixes `TypeError: argument of type 'NoneType' is not iterable` by testing `platform_name`'s argument type first
```
File "/home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/ci/build_platform.py", line 219, in install_platform
install_platform("arduino:avr")
File "/home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/ci/build_platform.py", line 220, in install_platform
if "daily" in platform_name: # manually install ESP32 BSP from latest source
TypeError: argument of type 'NoneType' is not iterable
```
=> Fix typerror in install_platform with AVR 

build_platform.py
Adding platform names for `feather_esp8266` and `feather_esp32` which alias `esp8266` and `esp32`
Why? Scripts which resource the platform name (`.arduino-platform`), i.e: `${{ matrix.arduino-platform }}.`, will generate files such as`wippersnapper.esp32.littlefs....bin`. These files do not contain the platform name, only the board name.
I'm adding these as duplicates since we use the `esp8266`/`esp32` platforms across a large # of libraries and this will be non-breaking (and mostly used for wippersnapper)
=> Better esp platform names

actions_install.sh
minor changes to add arduino-cli $GITHUB_PATH as opposed to export.
=> correctly add arduino-cli to PATH

build_platform.py
Uses a modified FQBN for `feather_esp8266` which is used by the WipperSnapper build CI
=> Use modified ESP8266 FQBN for ESP_8266

build_platform.py
The Adafruit Feather ESP32 v2 was included in ESP32 Arduino 2.0.3-RC1 release, removing `_daily` suffix from the feather esp32 v2's key as we no longer need to build from arduino-esp32's `master` branch
=> Update for ESP32 Feather v2

build_platform.py
Fixes `Invalid argument passed: Found 0 platform for reference "espressif:esp32":` caused by https://github.com/adafruit/ci-arduino/commit/e3c616667676db26f236dec73a84039e640cc0af
=> Use correct FQBN for Feather ESP32 V2

build_platform.py
Adding support for Feather ESP32-S3 and QT Py ESP32-S3
ESP32-S3 Board Family ID from https://github.com/microsoft/uf2/blob/master/utils/uf2families.json#L158
=> Add Feather ESP32-S3, QT Py ESP32-S3

build_platform.py
Fixes AVR platforms not compiling due to https://github.com/adafruit/ci-arduino/pull/132.
Tested locally against the Adafruit Learning System repo with feather32u4 and gemma platforms.
@ladyada  We may want to add the following platforms: adafruit:avr, esp32s2, esp32c3, esp32s3 to https://github.com/adafruit/ci-arduino/blob/master/.github/workflows/githubci.yml#L19 in the future.
=> Fix AVR platforms not compiling 

actions_install.sh
As the default image already has v10, v11 (default) and v12 installed, you don't have to install v8 and don't even use it. This removes the need for a long (most of the time 2 minutes) mirror search or even call `apt-get install` in the first place. This shortens the time spent in `actions_install.sh` from about 2:30min to 6s, which is 25x faster.
This is similar to PR #135, but wraps it in a conditional: if the search for `/usr/bin/clang-format` fails, install it. This should be fully backwards compatible.
This is the output of `clang-format --version` with this change:
This as it was before:
There is no difference, as both times the defaut `clang-format` gets used.
=> Only install clang-format if it is really missing

example_actions.yml
This change reorders the actions so the least expensive and most failing actions are run first. On a typical run, doxygen and clang-format take each about 2s, the complete building on all the supported platforms 10 minutes. In my experience, the most fails I get are from formatting and documentation errors, not from compilation problems. This gives the users a much faster feedback on needed changes in their commits and PRs and shaves off a lot of execution time.
If you also consider accepting PR #135, this gives the user feedback on formatting and documentation in under 30s, compared to before after 13 minutes.
=> reordered the actions, so clang-format and doxygen are run first

build_platform.py
Adding build support for [Adafruit QT Py ESP32 Pico](https://www.adafruit.com/product/5395).
Tested locally against WipperSnapper Arduino Library
=> Build for Adafruit QT Py ESP32 Pico

build_platform.py
Adding QT Py ESP32-C3
Notes:
Flash mode is defined as QIO, temporarily fixing an issue with LittleFS corruption (see: https://github.com/espressif/arduino-esp32/issues/6579). I will update ci-arduino to remove this from the FQBN once EspressIf patches and releases this fix.
=> Add Adafruit QT Py ESP32-C3

build_platform.py
Fixes FQBN for QT Py ESP32-S3 to match https://github.com/espressif/arduino-esp32/blob/master/boards.txt#L8148
=> Fix FQBN for QT Py S3

.github/workflows/githubci.yml, actions_install.sh
Since rebuild trigger workflow use `arduino-library` tag in topics to determine which repo is an Arduino Library. Although I manually added this tag for all of our repo, I could miss several and/or it is easy for us to forget add this when making an new repo/lib.
This PR will throw an warning if action_install.sh is used by other repo and the repo does not have `arduino-library` in its topic. e.g
This hopefully over time will help us to get all repo tagged and triggered.
=> throw warnings if action_install.sh is used and repo does not have 'arduino-library' tag in its topic

build_platform.py
Adds build platforms for PicoW w/PicoSDK USB stack and PicoW w/TinyUSB USB stack
=> Add PicoW and PicoW_TinyUSB

build_platform.py
* Temporarily using a gist for the latest (05/04/23) archive of `package_drazzy.com_index.json` hosted on https://web.archive.org/web/20230504110614/http://drazzy.com/package_drazzy.com_index.json
Related issue: https://github.com/SpenceKonde/megaTinyCore/issues/968
Failing: https://github.com/adafruit/Adafruit_LvGL_Glue/actions/runs/5204831513/jobs/9389611039#step:7:20
=> Fix FAILED to update core indices 

build_platform.py
@brentru I was getting flashing errors using the latest CI builds for the PicoW, but v71 (using old CI) works. 
It appears we don't have a storage partition so I've updated the flash defs, also doing the frequencies while at it (133MHz is top before overclocking).
I did the 8mb boards too, but maybe I should restrict my changes to the tiny_usb definitions of flash partitions, and all rp2040 frequencies.
=> Update pico flash params

build_platform.py
URL was removed as a temporary workaround in #158. The URL seems to be working again, so this PR puts it back.
=> Put back megatinycore BSP URL

build_platform.py
This is hack to get around an issue with the current version of `arduino-cli` that mangles some BSP URLs:
https://github.com/arduino/arduino-cli/issues/2345
This PR uses the suggested fix from:
https://github.com/SpenceKonde/megaTinyCore/issues/1005
to simply rename to file to its expected name.
=> Hack fix for arduino-cli issue with megatinycore BSP URL

actions_install.sh
- Fix running CI in private repo
Description:
CI was failing at pre-install step because it was trying to get repo topics of a private repo. Added a fallback string incase `curl` returns `null` due to unauthorized response from Github.
=> Fix for running ci-arduino in private repos

actions_install.sh, all_platforms.py
This PR:
- adds two itsybitsy_rp2040 definitions, normal + TinyUSB variants of the ItsyBitsy RP2040, both currently setup with 512k assigned to filesystem partition.
- adds FunHouse No OTA definition `funhouse_noota`
- adds ItsyBitsy ESP32 definition
- adds debug entry for adafruit_feather_esp32s3_reversetft.
- fixes an issue with reading the topics of a GH repo if the repo is private/404 when checking for arduino-library
=> Add ItsyBitsy RP2040 and FunHouse_NoOTA targets, fix repo_topics, include RevTFT S3 feather in debug builds

build_platform.py
@ladyada / @caternuson I did this last time to unblock us, instead of removing the Drazzy link, but maybe it can be a long term fix.
This is a domain that I own, with multiple year validity and auto-renew (with account credit and calendar reminders).  
It's DNS is hosted on Cloudflare, and I've created a subdomain using Cloudflare proxy that points at Drazzy.com but using Cloudflare's SSL certificate (zero cost).
https://drazzy.good-enough.cloud (all url paths will forward)
i.e. the new BSP path becomes 
https://drazzy.good-enough.cloud/package_drazzy.com_index.json
=> Add HTTPS mirror of Drazzy.com served through cloudflare

.github/workflows/githubci.yml, build_platform.py
This PR move most of global code and variable into main() function, remove ussage of global fqb/platform/platforms in other funtions. This allow build_platform.py can be immported by other python script. And can run `test_examples_in_folder()` without installing the core platform.
The reason is BSP_URL is using arduino-esp32 dev json --> install esp32 v3.0.0 alpha. Some libraries such as TinyUSB need to run with both v3.0.0 (dev) and v2.0.15 since espressif update libtinyusb often and can cause version mismatch.
This changes allow other lib can manually install arduino core (e.g esp v2) then execute tests as done in https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/414/files#diff-4951824edd423ca1a60532c1baf26ddf0b20f04791e15628c1de91c0200051d3R86
also fix is_library_installed() …
=> Importable build platform

.github/workflows/githubci.yml, all_platforms.py, build_platform.py
add CH32V20x_EVT board to supported platform
Note: also add 2 line separation before function definition per `PEP 8: E302 expected 2 blank lines`
=> add ch32v2 core from openwch

all_platforms.py
Hey @brentru I've added a couple of build options to the C6 feather wippersnapper build target:
`esp32:esp32:adafruit_feather_esp32c6:UploadSpeed=921600,CDCOnBoot=cdc,CPUFreq=160,FlashFreq=80,FlashMode=qio,PartitionScheme=min_spiffs`
=> Update all_platforms.py - set C6 feather to CDC on for WipperSnapper

build_platform.py
change esp32 package json index from beta to stable (official). Due to an issue with 3.1.0-RC when building with tinysb library. It is fixed in their latest release/v3.1 branch. Also currently we have no need for RC release, I think we historically use it when espressif introduce esp32s2 or so.
merged now for https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/466, we can revert this should there is an issue
=> change esp32 package json to stable one

.github/workflows/githubci.yml, all_platforms.py
.. so we can check if Adafruit_Floppy builds on the feather rp2350 hstx: https://github.com/adafruit/Adafruit_Floppy/pull/50
=> Add feather rp2350 to all_platforms

README.md, doxy_gen_and_deploy.sh
this will let us have other website pages hosted!
=> Add PRESERVE_FOLDERS feature to documentation generation script

all_platforms.py
Updates Fruit Jam to use an 8/8MB app/user partition
=> Fix flash size for fruit_jam_tinyusb entry
